config/routes.rb
Rails.application.routes.draw do
  root 'welcome#bemvindo'
  resources :clientes

  get "inicio" => "welcome#bemvindo"
  get "produto" => "produto#produts"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:name, :phone_number)
    end
end

app/controllers/produto_controller.rb
class ProdutoController < ApplicationController
    def produts
        @lista=['camisas', 'canecas', 'chinelos', 'garrafas', 'adesivos', 'banners', 'postesr', 'cestas', 'fotos' ]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def bemvindo
       @logo = 'SVD Gráfica'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/produto_helper.rb
module ProdutoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Name:</strong>
    <%= cliente.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= cliente.phone_number %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<%#Edição de clientes%>

<h1>Editando dados</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Show this cliente", @cliente %> |
  <%= link_to "Volte para a Home",inicio_path %>
</div>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>


<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
    <p>
      <%= link_to "Ver mais do cliente", cliente %>
    </p>
  <% end %>
</div>

<%= link_to "Voltar a Home", inicio_path %>

app/views/clientes/new.html.erb
<%#<div>
<h2>
<span class="S">S</span>
<span class="V">V</span>
<span class="D">D</span>
<h2>
</div>%>
<center>
<h3>Novo Cadastro</h3>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Volte ao inicio", "/inicio" %>
</div>

</center>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cliente %>

<div>
  <%= link_to "Editar cliente", edit_cliente_path(@cliente) %> |
   <%= link_to "Volte ao inicio", inicio_path%>

  <%= button_to "Destroy", @cliente, method: :delete%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Svd Gráfica</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  </h1><h1>
    <%= yield %>
  </body>
</html>

app/views/produto/produts.html.erb
<%#<img src="SVD.jpg">
<header> %>

<div>
<h2>
<span class="S">S</span>
<span class="V">V</span>
<span class="D">D</span>
<h2>
</div>

<center>
  <nav>
   <h6> <a href= '/inicio'>Home</a>
    <a href='/produto'>Produtos</a>
    <a href='/clientes/new'>Cadastro</a>
    <h6>
  </nav>
</center>

  <form>
    <input placeholder='Pesquisar'/>
    <button>Enviar</button>
  </form>

</header>
<h4>
<%= @lista %>
<h4>

app/views/welcome/bemvindo.html.erb
<header> 

<div>
<h2>
<span class="S">S</span>
<span class="V">V</span>
<span class="D">D</span>
<h2>
</div>

<center>
  <nav>
   <h6> <a href= '/inicio'>Home</a>
    <a href='/produto'>Produtos</a>
    <a href='/clientes/new'>Cadastro</a>
    <h6>
  </nav>
</center>

  <form>
    <input placeholder='Pesquisar'/>
    <button>Buscar</button>
  </form>

<h6>Aqui você encontra canecas, camisetas e muitas outras personalizações<h6>